baseURL = "mycclp.github.io/site-cclp-main"
languageCode = "en-us"
title = "文化中国"
theme = "hugo-minimal"
googleAnalytics = ""

[params]
    author = "Steve Shao"
    description = "浙江大学 晨兴 文化中国 人才计划 校友会"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"

[[menu.main]]
    url = "/"
    name = "主页"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "关于我们"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "博客文章"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "资源"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/MYCCLP"
    name = "github"
    weight = 1
